runtime: python313
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: "ubuntu22"

handlers:

- url: /scripts
  static_dir: static/scripts

- url: /styles
  static_dir: static/styles

- url: /images
  static_dir: static/images

- url: /.*
  script: auto
