application: yijiaowushu-hrd
version: 2016-07-31
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: jinja2
  version: latest


handlers:

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /.*
  script: cwta.app

inbound_services:
- warmup
