#!/bin/sh

#
# I created this file because the updates for CWTA are infrequent, and every time I have to do them
# I've forgotten what commands I need to run to get the dev env up
#

echo Updating GCloud Components...
gcloud components update


# dev_appserver.py ~/code/cwta/redesign/website
# python3 /Users/gregmli/Applications/google-cloud-sdk/bin/dev_appserver.py ~/code/cwta/redesign/website
python3 ~/code/cwta/redesign/website/main.py

echo When you are ready to deploy changes:
echo "> gcloud app deploy"
echo
echo add the --promote option to make this the default version as well
